# Generated by Django 5.1.5 on 2025-01-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preview_image', models.ImageField(upload_to='template_previews/')),
                ('html_file', models.FileField(upload_to='template_html/')),
            ],
        ),
    ]
