# Generated by Django 5.1.5 on 2025-01-19 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.businessdetails')),
                ('selected_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.template')),
            ],
        ),
    ]
